# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - 1.4
  - nightly
notifications:
  email: false
git:
  depth: 999999

coveralls: true
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: 1.2
      script: julia --project=docs -e '
        using Pkg;
        Pkg.develop(PackageSpec(path=pwd()));
        Pkg.instantiate();
        include("docs/make.jl");'
      after_success: skip
